### ISSUE TITLE
package installation from source error 

### ISSUE THREAD

**Issue by pkraison** [tinygrad/gpuctypes#9]
I cloned the repository and tried installing on my Ubuntu 20.04 with Python 3.7.13. It gave the error regarding the python version requirement.

**Comment by pkraison** [comment]
I noticed in the setup.py has this requirement mentioned '>=3.8'. I just changed it to '>=3.7' and it worked.

**Comment by pkraison** [comment]
I got the point, It needs python 3.8.

**Comment by geohot** [comment]
The types and walrus should only be the tests, shouldn't affect the package

**Comment by pkraison** [comment]
yes, tried without it and it worked. thanks!
